### ISSUE TITLE
Feature request: anchors for at least section headers

### ISSUE THREAD

**Issue by bbannier** [bearcove/feedback#2]
While I do enjoy your long-form writing style, your articles contain almost no anchors which makes it hard to point others to specific parts (I usually use https://github.com/Rob--W/display-anchors to pick nearby anchors). It would be great if you could consider adding anchors to at least section headers, but having them on more elements (e.g., code samples) would be even better.

**Comment by jasikpark** [comment]
Maybe checking out something like https://github.com/imcuttle/remark-heading-id might help make this implementable - I believe you could just hash the content or count the heading number if you wanted to. 

`# hello world` -> `<a href="#hello_world_adkdf9e33"><h1 id="hello_world_adkdf9e33">hello world</h1></a>`

**Comment by jasikpark** [comment]
woot header linkkkkks

**Comment by fasterthanlime** [comment]
By popular request: it is done! https://www.patreon.com/posts/66106104

Enjoy :)

**Comment by fasterthanlime** [comment]
> woot header linkkkkks

@jasikpark haha did you somehow notice them between my deploy and my announcement post?

**Comment by jasikpark** [comment]
> > woot header linkkkkks
> 
> @jasikpark haha did you somehow notice them between my deploy and my announcement post?

lol i saw the patreon post notif "fasterthanlime posted x 45sec ago"
