### ISSUE TITLE
Article issue

### ISSUE THREAD

**Issue by robinmoussu** [bearcove/feedback#208]
## It happened on this page

https://fasterthanli.me/series/building-a-rust-service-with-nix/part-9

## Here's what the issue is

> The following is a verbatim copy of what I wrote on reddit

I’m not convinced about the “Tired of reading?” insert. It does feel odd to have a link to a relatively unrelated video in the middle of the article. Maybe it would be better placed at the end?

And also I’m not sure if it’s possible to move the header (it does have those classes: `ytp-chrome-top ytp-show-cards-title`) above the embedded video, or at least make its background more opaque. It’s because, at least for the video “Fine, I'll tell you how feature flags work (but I'll brag about my Rust blog engine while doing it)”, you do have text at the top of the video miniature, making the whole thing hard to read.

**Comment by fasterthanlime** [comment]
I ended up removing that.
