### ISSUE TITLE
Linking to Twitter

### ISSUE THREAD

**Issue by BurntNail** [bearcove/feedback#209]
## It happened on this page
[Just around the part mentioning 8 bits to a byte after complaining about go's unsafe package.](https://fasterthanli.me/articles/whats-in-the-box#a-practical-and-very-innocent-example)
## Here's what the issue is

Not sure if this is an issue - here you link to your Twitter (as part of asking people to send photos of non-8 bit bytes), but should you be linking to your Mastodon instead?

**Comment by desmodrone** [comment]
Thanks for the feedback, this is not an issue :)
