### ISSUE TITLE
Consider using long command line options

### ISSUE THREAD

**Issue by Hofer-Julian** [bearcove/feedback#211]
When reading the articles I am often distracted by wondering what command line options actually do. Most of the time there are long alternatives to the short ones used in your tutorials. Using these, would, at least for me, make the articles even more enjoyable.
Thank you!

**Comment by fasterthanlime** [comment]
Can you report specific occurrences? I already do and try to do that, so if you find some, they're probably oversights and I'd like to fix them (but I also don't feel like going through EVERYONE ONE OF MY ARTICLES right now).

**Comment by Hofer-Julian** [comment]
Fair enough, I will spin up the PC and send a list of the ones I've found.

**Comment by Hofer-Julian** [comment]
https://fasterthanli.me/series/building-a-rust-service-with-nix/part-2:
  -  `sfz -b 0.0.0.0` -> `sfz --bind 0.0.0.0` (multiple times)
  - `curl -v -I http://10.0.2.15:5000` -> `curl --verbose --head http://10.0.2.15:5000`
  - `curl -I http://localhost:5000` -> `curl --head http://localhost:5000`

**Comment by Hofer-Julian** [comment]
https://fasterthanli.me/series/building-a-rust-service-with-nix/part-3

- `cargo add tokio@1 -F full` -> `cargo add tokio@1 --features full` (also fix other mentions of `-F` in the article)
- `git commit -m "Initial import"` -> `git commit --message "Initial import"`
- `git branch -M main` -> `git branch --move --force main`
- `git branch -l` -> `git branch --list`
- `git push -u origin main` -> `git push --set-upstream origin main` (makes the explanation above partially redundant)
- `git commit -m "Add README"` -> `git commit --message "Add README"`

**Comment by Hofer-Julian** [comment]
https://fasterthanli.me/series/building-a-rust-service-with-nix/part-4

- `cargo add tracing-subscriber@0.3 -F json` -> `cargo add tracing-subscriber@0.3 --features json` (also other mentions of `-F`)
- `git commit -m "Add crash reporting with Sentry"` -> `git commit --message "Add crash reporting with Sentry"`

**Comment by Hofer-Julian** [comment]
https://fasterthanli.me/series/building-a-rust-service-with-nix/part-5

- `lsb_release -a` -> `lsb_release --all`
- `docker build -t catscii .` -> `docker build --tag catscii .` (multiple times)
- `du -sh target/` -> `du --summarize --human-readable target/`
- `curl -Is archive.ubuntu.com | grep -i server` -> `curl --head --silent archive.ubuntu.com | grep --ignore-case server`

**Comment by pyrox0** [comment]
I've found some more short options in the Building a Rust Service with Nix series, with replacements provided:

[Part 6](https://fasterthanli.me/series/building-a-rust-service-with-nix/part-6):
- `fly config save -a old-frost-6294` -> `fly config save --app old-frost-6294`
- `docker run -it --env SENTRY_DSN --env HONEYCOMB_API_KEY -p 8080:8080/tcp --rm catscii` -> `docker run -it --env SENTRY_DSN --env HONEYCOMB_API_KEY --publish 8080:8080/tcp --rm catscii`

[Part 7](https://fasterthanli.me/series/building-a-rust-service-with-nix/part-7):
- `curl -o /dev/null -H 'fly-client-ip: 8.8.8.8' localhost:8080` -> `curl --output /dev/null --header 'fly-client-ip: 8.8.8.8' localhost:8080`
- `apt install -y --no-install-recommends \` -> `apt install --yes --no-install-recommends \`(This is inside the Dockerfile, though you may still want to do this, considering that in Part 8, the full argument `--yes` is passed to an `apt autoremove` call.)
- `mkdir -p ~/.ssh/ && ssh-keyscan ssh.shipyard.rs >> ~/.ssh/known_hosts` -> `mkdir --parents ~/.ssh/ && ssh-keyscan ssh.shipyard.rs >> ~/.ssh/known_hosts`


[Part 8](https://fasterthanli.me/series/building-a-rust-service-with-nix/part-8):
- `cargo update -p thiserror` -> `cargo update --package thiserror`
- `tar pfx GeoLite2-Country_20230214.tar.gz` -> `tar --preserve-permissions --extract --file GeoLite2-Country_20230214.tar.gz`
- `ls -lhA` -> `ls --long --header --almost-all`
- `apt install -y --no-install-recommends \` -> `apt install --yes --no-install-recommends \`(Multiple times)

[Part 9](https://fasterthanli.me/series/building-a-rust-service-with-nix/part-9):
- `sh <(curl -L https://nixos.org/nix/install) --daemon` -> `sh <(curl --location https://nixos.org/nix/install) --daemon`
- `nix-shell -p cowsay` -> `nix-shell --packages cowsay`
- `strace cowsay "Well well well" 2>&1 | grep -F '"/'` -> `strace cowsay "Well well well" 2>&1 | grep --fixed-strings '"/'`
- `nix eval -f` -> `nix eval --file`(Appears many times)
- `nix-store -r` -> `nix-store --realize`

[Part 10](https://fasterthanli.me/series/building-a-rust-service-with-nix/part-10):
- `head .envrc | grep -oE 'export [^=]+'` -> `head .envrc | grep --only-matching --extended-regexp 'export [^=]+'`

[Part 11](https://fasterthanli.me/series/building-a-rust-service-with-nix/part-11):
- `git commit -m "Ahhhh."` -> `git commit --message "Ahhhh."`
- `ls -lhA` -> `ls --long --header --almost-all`
- `gunzip -c result > /tmp/image.tar && dive docker-archive:///tmp/image.tar` -> `gunzip --stdout result > /tmp/image.tar && dive docker-archive:///tmp/image.tar`
- `sudo chown -R amos:amos /var/run/docker.sock` -> `sudo chown --recursive amos:amos /var/run/docker.sock`
- `docker run --rm -p 8080:8080 catscii:latest` -> `docker run --rm --publish 8080:8080 catscii:latest`
- `docker run --rm -e SENTRY_DSN -e HONEYCOMB_API_KEY -e GEOLITE2_COUNTRY_DB -e ANALYTICS_DB -p 8080:8080 catscii:latest` -> `docker run --rm --env SENTRY_DSN --env HONEYCOMB_API_KEY --env GEOLITE2_COUNTRY_DB --env ANALYTICS_DB --publish 8080:8080 catscii:latest`
- `docker run --rm -e SENTRY_DSN -e HONEYCOMB_API_KEY -e ANALYTICS_DB -p 8080:8080 catscii:latest` -> `docker run --rm --env SENTRY_DSN --env HONEYCOMB_API_KEY --env ANALYTICS_DB --publish 8080:8080 catscii:latest`
- `docker run --rm -e RUST_LOG=libhoney::transmission=trace -e SENTRY_DSN -e HONEYCOMB_API_KEY -p 8080:8080 catscii:latest` -> `docker run --rm --env RUST_LOG=libhoney::transmission=trace --env SENTRY_DSN --env HONEYCOMB_API_KEY --publish 8080:8080 catscii:latest`
- `curl -I https://aws.random.cat` -> `curl --head https://aws.random.cat`

[Part 12](https://fasterthanli.me/series/building-a-rust-service-with-nix/part-12):
- `cargo tree -i openssl-sys` -> `cargo tree --invert openssl-sys`
- `cargo tree -i rusqlite` -> `cargo tree --invert rusqlite`
- `cargo add tokio -F fs,test-util` -> `cargo add tokio --features fs,test-util`

**Comment by desmodrone** [comment]
Thank you @Hofer-Julian and @theHedgehog0 for the work you've put into the finding these. I've gone through and corrected short command line options with their longer, more descriptive alternatives that you both have provided. Cheers!
