### ISSUE TITLE
`nixpkgs.url` explanation on 2nd example

### ISSUE THREAD

**Issue by lutzky** [bearcove/feedback#217]
## It happened on this page

https://fasterthanli.me/series/building-a-rust-service-with-nix/part-10#a-flake-with-derivation

## Here's what the issue is

The following text:

```
    # this is equivalent to `nixpkgs = { url = "..."; };`
```

appears the 2nd time `nixpkgs.url` is used, and not on the first.

(nitpicker extraordinaire here)

**Comment by desmodrone** [comment]
@lutzky thanks for the eagles eyes ;)
