### ISSUE TITLE
Article issue

### ISSUE THREAD

**Issue by lutzky** [bearcove/feedback#218]
## It happened on this page

https://fasterthanli.me/series/building-a-rust-service-with-nix/part-10#adding-missing-dependencies

## Here's what the issue is

Earlier:

```
          # new! 👇
          nativeBuildInputs = with pkgs; [ rustToolchain pkg-config ];
          # also new! 👇
          buildInputs = with pkgs; [ openssl ];
```

...later:

```
          buildInputs = with pkgs; [ rustToolchain openssl sqlite ];
```

Did `rustToolchain` migrate from `nativeBuildInputs` to `buildInputs`? Or is it now required in both?

**Comment by fasterthanlime** [comment]
> Or is it now required in both?

I don't think it is! I think I just messed up.

In my internal projects it's just in `nativeBuildInputs` and that's fine.

(I updated the article accordingly)
