### ISSUE TITLE
Making a dev shell with nix flakes - breaks VSCode proc-macro?

### ISSUE THREAD

**Issue by lutzky** [bearcove/feedback#219]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-10

After running alongside the article (got to "`cargo run` works"), rust-analyzer shows the following warning:

> Failed to spawn one or more proc-macro servers.
> 
> Failed to find sysroot for Cargo.toml file /home/ubuntu/catscii/Cargo.toml. Is rust-src installed? can't load standard library from sysroot
> 
> /nix/store/2fj9l29hd5is09ccqcf3rd4srrmz2bza-rust-default-1.68.0-nightly-2022-12-24
> 
> (discovered via `rustc --print sysroot`)
> 
> try installing the Rust source the same way you installed rustc

Analysis seems to work otherwise, but not all type annotations are there (e.g. `headers.get` is missing). Not a clue why.

**Comment by fasterthanlime** [comment]
So I ran into this recently and it works if you add the `rust-src` component into your `rust-toolchain` file!

I edited part 7 (!) to include that.
