### ISSUE TITLE
Search bar typing scrolls up page on Chromium-based browsers

### ISSUE THREAD

**Issue by W-tungsten** [bearcove/feedback#221]
I found something wrong on this page:

  https://fasterthanli.me/#position=0.0

  Here's what it is:

 Every time I type a character in the search bar, it scrolls up slightly. This happens on any page on your website. This happened on Edge and Brave, but not on Firefox (I think it has something to do with Chromium)

**Comment by fasterthanlime** [comment]
I've fixed this! Somehow `position: sticky` was involved in the mix-up. I switched (back) to `position: fixed` for this and adjusted a bunch of other things. The overall layout could probably use a redo sooner rather than later anyway.
