### ISSUE TITLE
Article issue

### ISSUE THREAD

**Issue by kbridge** [bearcove/feedback#222]
## It happened on this page

https://fasterthanli.me/series/building-a-rust-service-with-nix/part-4

## Here's what the issue is

> Then install a handler, and log something to say we're listening on the address we're listening on:
>
> (code)

The code should be prepended:

> use std::str::FromStr;

Otherwise Rust compiler will complain about `Targets::from_str()`.

**Comment by desmodrone** [comment]
good catch @kbridge fixed this one!
