### ISSUE TITLE
Deploying catscii to fly.io

### ISSUE THREAD

**Issue by kbridge** [bearcove/feedback#227]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-6#position=2.0

Here's what it is:

In my case, I found that you have to [launch](https://fly.io/docs/flyctl/launch/) an App before saving its config locally.

Just creating an App is not enough. Saving config immediately after `fly apps create` results in:

```txt
ubuntu@lime:~$ fly apps create
(cut)
New app created: wandering-sky-6854
ubuntu@lime:~/catscii$ fly config save --verbose -a wandering-sky-6854
Error: failed to grab app config from existing machines, error: could not create a fly.toml from any machines :-(
No machines configured for this app
```

Launching an App creates a `fly.toml`. So you don't need to dump one with `fly config save` manually.

**Comment by desmodrone** [comment]
@kbridge thank you for your feedback! I've added a note to the tutorial for those users that might be experiencing the same issue.
