### ISSUE TITLE
Learning Nix from the bottom up

### ISSUE THREAD

**Issue by kbridge** [bearcove/feedback#236]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-9#position=67.0

Here's what it is:

Running `nix show-derivation` yields a warning (two warnings, actually):

    warning: 'show-derivation' is a deprecated alias for 'derivation show'
    warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/vsa6cnidqwfbhs35g0d4r7f9fazyg2av-dive-0.10.0.drv!*'

**Comment by fasterthanlime** [comment]
Fixed, thanks!
