### ISSUE TITLE
The HTTP crash course nobody asked for meets the pedantic nobody asked for

### ISSUE THREAD

**Issue by olepbr** [bearcove/feedback#239]
I found something wrong on this page:

  https://fasterthanli.me/articles/the-http-crash-course-nobody-asked-for#position=63.9

  Here's what it is:

In the code snippet, we have the following comment:

```rust
/// See https://httpwg.org/specs/rfc9113.html#FrameHeader - the first bit
/// is reserved, and the rest is a 32-bit stream id
```

The linked RFC says that the stream identifier is "expressed as an unsigned 31-bit integer", so to my eyes it looks like we have an off-by-one error in the comment =)

**Comment by desmodrone** [comment]
good catch, thank you!
