### ISSUE TITLE
fasterthanli.me URL handling

### ISSUE THREAD

**Issue by Bert-Proesmans** [bearcove/feedback#240]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-Nix/part-9#position=0.0

  Here's what it is: your urls are case sensitive, the above url contains [..]with-**N**ix/[..], resulting in a 404 after improperly copying. The url that resolves has a lowercase N.
Up to you if a compatibility fix is a good idea or not.

**Comment by fasterthanlime** [comment]
I'm fine with URLs being case-sensitive for now!
