### ISSUE TITLE
Making a dev shell with nix flakes

### ISSUE THREAD

**Issue by pyrox0** [bearcove/feedback#242]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-10#position=61.1

  Here's what it is:
  
  You mention being able to "fix" the problem of duplicated inputs by overridding them with a `follows` attribute. However, the key problem with this(and why it's not the default behavior` is that if you don't use the exact same version of the inputs(I mean literally same version, down to the commit), you can end up in a "rebuilding the world" situation, where you have to build stuff from source without being able to pull from a [Binary Cache](https://nixos.wiki/wiki/Binary_Cache). Because you have different inputs, there is the possibility of creating a differently-hashed output, and thus the hash is invalidated and you need to build from source. 
  
  This is not a problem in the example you provide, because `rust-overlay` is really just generated fetchers for prebuilt binaries, but this becomes a problem with something like [emacs-overlay](https://github.com/nix-community/emacs-overlay), when you can end up building Emacs from source, which can take a while(10-15 min for me on my Framework 11th gen i5, but can take an hour or much longer on an old 2-core Macbook Air!)
  
  Thus, while it's not technically "wrong" by any standard, it would probably be best to include a disclaimer that this can make things take longer because more has to(potentially) built from source.

**Comment by fasterthanlime** [comment]
Thanks, I added a link to your explanation!
