### ISSUE TITLE
Questionable line overflow splitting

### ISSUE THREAD

**Issue by lyssieth** [bearcove/feedback#243]
So, browsers and other text rendering engines probably think that `--` is fine to put a newline in between, _but_

I was reading the "Extra Credit" article and spotted this... rather ugly newline, and I feel like there _must_ be some way to fix it, surely? Especially for flags and such?

I don't have a blog (yet, oh god) otherwise I'd have to figure this out myself :)

![image](https://github.com/fasterthanlime/feedback/assets/1861988/aa00a14a-89b8-432d-9e3c-1a1e4c26eed5)

**Comment by jasikpark** [comment]
gotta slap some word break rule on code spans ig?

**Comment by desmodrone** [comment]
@lyssieth Thank you. This was hard to read. I fixed the sentences for readability, we'll look into different ways to fix this in the future.

**Comment by lyssieth** [comment]
Okay, great!

**Comment by fasterthanlime** [comment]
> gotta slap some word break rule on code spans ig?

This probably warrants a separate issue fwiw @desmodrone
