### ISSUE TITLE
Remote development with Rust on fly.io

### ISSUE THREAD

**Issue by lecanard539** [bearcove/feedback#244]
I found something wrong on this page:

  https://fasterthanli.me/articles/remote-development-with-rust-on-fly-io#position=4.0

  Here's what it is:

Small spelling mistake, it's faHrenheit, not farenheit.

Un grand merci pour ton travail! J'aime boucoup les articles de Rust. J'ai déjà fait un petit don.

**Comment by desmodrone** [comment]
Fixed, thank you!
