### ISSUE TITLE
Making a dev shell with nix flakes

### ISSUE THREAD

**Issue by mfsch** [bearcove/feedback#247]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-10#position=87.2

 Here's what it is: In the paragraph

> It's easier to remember if you think of cross-compiling: if you're building for x86_64 from aarch64, you might be using a "native" GCC for x86_64, that generates aarch64 binaries, hence: native build inputs.

I think it should say “if you're building for aarch64 from x86_64” or “from x86_64 for aarch64” instead.

**Comment by desmodrone** [comment]
Thank you!
