### ISSUE TITLE
Learning Nix from the bottom up

### ISSUE THREAD

**Issue by iFreilicht** [bearcove/feedback#250]
I found something that could be improved on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-9#position=54.6

  Here's what it is:

> What is system set to? Let's find out: […]
> Woops, that didn't work. Does nix eval not give you builtins? […]
> Oh, it does. It just doesn't have currentSystem.

I found this to be a little confusing and would’ve liked an explanation. Because you used `--impure` earlier in the article, I was able to piece together that pure evaluation was the issue, and indeed, using `--impure` works just fine:

```
$ nix eval --impure --eval ‘builtins.currentSystem’
“aarch64-darwin”
```

Maybe it would be better to show this instead of just jumping to the repl and not understanding why it works there but not with eval.

**Comment by desmodrone** [comment]
@iFreilicht thank you for this, I've added some notes to help clear things up.
