### ISSUE TITLE
Article issue

### ISSUE THREAD

**Issue by kbridge** [bearcove/feedback#251]
## It happened on this page

https://fasterthanli.me/series/building-a-rust-service-with-nix/part-11

Search for the code snippet under "Let's keep going".

## Here's what the issue is

Comments in this code snippet seem like mixing tabs and spaces. Plus the page displays code snippets with a tab width of 2. Cause indentation issues.

**Comment by desmodrone** [comment]
Thanks for the feedback, this should be fixed!
