### ISSUE TITLE
Rust modules vs files: There is no "2022 edition"

### ISSUE THREAD

**Issue by TheEyesightDim** [bearcove/feedback#253]
I found something wrong on this page:

  https://fasterthanli.me/articles/rust-modules-vs-files#position=0.0

  Here's what it is: 
  
You say "All that follows is written for Rust 2022 edition" and mention setting `edition = 2022` in the `cargo.toml`, but as far as I can tell this edition doesn't exist, and as of Cargo 1.72 Nightly, will complain if you try to build a rust project with that value set.

[This shows that Cargo only accepts 2015, 2018, and 2021 as edition strings.](https://github.com/rust-lang/cargo/blob/0c14026aa84ee2ec4c67460c0a18abc8519ca6b2/src/cargo/core/features.rs#L322)

**Comment by fasterthanlime** [comment]
I got discord-shamed into fixing it. Thanks for your report!
