### ISSUE TITLE
Article issue

### ISSUE THREAD

**Issue by CharlyCst** [bearcove/feedback#254]
## It happened on this page

[In the bowels of glibc](https://fasterthanli.me/series/making-our-own-executable-packer/part-14), near the beginning.

## Here's what the issue is

Missing a few words:

"So far, most of the programs we've been able using our "runtime linker/loader" were purpose-built for it."

Should be something like:

"So far, most of the programs we've been able **to execute** using our "runtime linker/loader" were purpose-built for it."

## Thanks

This series is awesome, thanks for sharing your work!

**Comment by desmodrone** [comment]
updated, thank you!

**Comment by CharlyCst** [comment]
You're welcome!
