### ISSUE TITLE
Writing a Dockerfile for catscii

### ISSUE THREAD

**Issue by Yarden-zamir** [bearcove/feedback#256]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-5#position=18.0

  Here's what it is:
![Screenshot_2023-07-11-00-00-21-607_com android chrome](https://github.com/fasterthanlime/feedback/assets/8178413/1d3c09ae-8fd3-4c67-94ba-203a49fd9804)

I have my font size set bigger which changes the text size but not the label behind it

**Comment by fasterthanlime** [comment]
Is this Chrome on Android or something else?

**Comment by Yarden-zamir** [comment]
Chrome on android. Pocofon f3 nfc. The font was one point above default size in accessibility settings

**Comment by fasterthanlime** [comment]
I looked at the DOM again and honestly this feels like a browser bug?

It's really just with some text in it and `width: auto`. It's really not supposed to spill like that. Oh well.
