### ISSUE TITLE
The curse of strong typing

### ISSUE THREAD

**Issue by spencerpogo** [bearcove/feedback#257]
I found something wrong on this page:

  https://fasterthanli.me/articles/the-curse-of-strong-typing#different-kinds-of-numbers

  Here's what it is:

May want to use https://en.m.wikipedia.org/wiki/Tau_(mathematical_constant) instead of the more general https://en.m.wikipedia.org/wiki/Tau here

**Comment by desmodrone** [comment]
Thank you for the more specific link!
