### ISSUE TITLE
Serving ASCII cats over HTTP

### ISSUE THREAD

**Issue by jasikpark** [bearcove/feedback#258]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-4#position=97.3

  Here's what it is:

I can't get `https://aws.random.cat/meow` to load for me.. 

<https://uptime.com/freetools/global-uptime-test/122742/aws.random.cat>

**Comment by desmodrone** [comment]
Right, it seems like https://cataas.com is now working, but https://aws.random.cat/meow is not, so we have to update the article. Thank you!

**Comment by fasterthanlime** [comment]
> Right, it seems like https://cataas.com is now working, but https://aws.random.cat/meow is not, so we have to update the article. Thank you!

We honestly should run our own cat-as-a-service API at this point lol

**Comment by fasterthanlime** [comment]
Fixed!
