### ISSUE TITLE
Peeking inside a Rust enum

### ISSUE THREAD

**Issue by SteveAlexander** [bearcove/feedback#259]
I found something wrong on this page:

  https://fasterthanli.me/articles/peeking-inside-a-rust-enum#position=96.0

  Here's what it is:

I wanted to read the explanation to "Update: it appears that the "high 16-bits" situation is not that simple". But I cannot.

It's a link to Twitter, and I can see your replies, but not what you're replying to. "You’re unable to view this Tweet because this account owner limits who can view their Tweets."

<img width="893" alt="image" src="https://github.com/fasterthanlime/feedback/assets/4321921/af728522-fa18-4c4b-8b30-2d2ac1e97592">

**Comment by fasterthanlime** [comment]
I'm afraid that thread is lost to time and/or buyouts. I've removed the link :(
