### ISSUE TITLE
video player: too many digits of volume percentage displayed

### ISSUE THREAD

**Issue by sharnoff** [bearcove/feedback#26]
<details>
<summary>Screenshot emphasizing the problem</summary>
The window was artificially very small; this doesn't affect the font size of the volume display, so it became relatively very large.
<img src="https://user-images.githubusercontent.com/29154784/165858833-f22017b4-b548-4732-809b-c123bea35323.png">
</details>

Steps to reproduce:

1. Adjust the volume level by clicking somewhere with the mouse (this will likely set it to a repeating decimal, e.g. 27.2727...)
2. Use the up/down arrow keys to change the volume, which now displays many digits of the volume percentage (which it has because arrow keys are exactly ±5%).

**Comment by fasterthanlime** [comment]
I made a fix, deploy is in progress - could be a few minutes.
