### ISSUE TITLE
Using the Shipyard private crate registry with Docker

### ISSUE THREAD

**Issue by jasikpark** [bearcove/feedback#260]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-7#position=56.5

  Here's what it is:

```diff
 -       match state.locat.ip_to_iso_code(addr).await {
 +       match state.locat.ip_to_iso_code(addr) {
            Some(country) => {
                info!("Got request from {country}");
                span.set_attribute(KeyValue::new("country", country.to_string()));
            }
            None => warn!("Could not determine country for IP address"),
        }
```

In the initial config of locat, an Option<_> is returned, with no await required, that must be added later in the next post when it is an async fn

**Comment by desmodrone** [comment]
Thank you @jasikpark
