### ISSUE TITLE
Doing geo-location and keeping analytics

### ISSUE THREAD

**Issue by jasikpark** [bearcove/feedback#261]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-8#position=27.5

  Here's what it is:

```
$ mv GeoLite2-Country_20230214/
COPYRIGHT.txt          GeoLite2-Country.mmdb  LICENSE.txt 
```

should be `ls`

**Comment by desmodrone** [comment]
thank you @jasikpark!
