### ISSUE TITLE
Day 2 (Advent of Code 2022)

### ISSUE THREAD

**Issue by abderrahimAMZ** [bearcove/feedback#263]
hi fasterthanlime, big fan here! i check your AoC answers to learn from them, i like how you solve them and the explaining is clear. however, i don't get why exactly why not just build the logic directly instead of implementing enums and structs. if you already have a blog, youtube video, explaining the thing, give me the link and don't waste your time.

**Comment by fasterthanlime** [comment]
> however, i don't get why exactly why not just build the logic directly instead of implementing enums and structs

So there's several reasons!

One reason to use types is so you remember what a thing is for. Let's say for example you have:

```rust
struct Person {
  first_name: String,
  last_name: String,
}
```

You can accidentally do something like:

```rust
person_a.last_name = person_b.first_name;
```

If instead you used types like:

```rust
struct Person {
  first_name: FirstName,
  last_name: LastName,
}
```

Then the compiler would've caught that. This code for example:

```rust
struct FirstName(String);
struct LastName(String);

struct Person {
    first_name: FirstName,
    last_name: LastName,
}

fn main() {
    let person1 = Person {
        first_name: FirstName("John".into()),
        last_name: LastName("Doe".into()),
    };

    let person2 = Person {
        first_name: FirstName("Jane".into()),
        last_name: LastName("Doe".into()),
    };

    person1.last_name = person2.first_name;

    println!("Hello, world!");
}
```

Gives us this error:

```shell
$ cargo c
    Checking whytypes v0.1.0 (/Users/amos/bearcove/whytypes)
error[E0308]: mismatched types
  --> src/main.rs:20:25
   |
20 |     person1.last_name = person2.first_name;
   |     -----------------   ^^^^^^^^^^^^^^^^^^ expected `LastName`, found `FirstName`
   |     |
   |     expected due to the type of this binding
```

This is a pretty contrived example, of course. But for example, I'd rather receive one of these:

```rust
struct Point3 {
  x: f64,
  y: f64,
  z: f64,
}
```

Than a `(f64, f64, f64)` or a `[f64; 3]`.

---

Of course you wouldn't necessarily have to go through intermediate types like I do, but for me it's just how i think about problems. Once you find the right data structure, solving the problem itself becomes trivial.
