### ISSUE TITLE
Terms and conditions

### ISSUE THREAD

**Issue by JosiahBull** [bearcove/feedback#265]
I found something wrong on this page:

  https://fasterthanli.me/terms-and-conditions#position=0.0

  Here's what it is:

> Donors may also use the "friend link" feature to share early access content **with their a few** friends or colleagues.

Has a small grammatical mistake, highlighted in bold.

**Comment by JosiahBull** [comment]
Note, your site is also missing a `robots.txt` file and site directory, if you think it's worth having them. :)

**Comment by fasterthanlime** [comment]
> Note, your site is also missing a `robots.txt` file and site directory, if you think it's worth having them. :)

Also a humans.txt file, but these ought to be separate issues!

**Comment by fasterthanlime** [comment]
> Note, your site is also missing a `robots.txt` file and site directory, if you think it's worth having them. :)

Oh actually I do have a `robots.txt`, it's just empty :)
