### ISSUE TITLE
Rust generics vs Java generics

### ISSUE THREAD

**Issue by tymscar** [bearcove/feedback#267]
I found something wrong on this page:

https://fasterthanli.me/articles/rust-vs-java-generics#position=20.5

Here's what it is:
There is a mispelling of `manifest` on the page. It's written as `maniest` in `you have to set up a maniest to be able to use the instrumentation package, and even then it's just an estimate of object sizes`.

**Comment by desmodrone** [comment]
@tymscar thank you for letting us know about this -- I've fixed the typo.
