### ISSUE TITLE
Suggestion for A half-hour to learn Rust

### ISSUE THREAD

**Issue by liffiton** [bearcove/feedback#268]
I'm interested in using A Half-Hour to Learn Rust as a resource for students in a programming languages class, but it won't be particularly helpful to just give them a link to the page and say "read this."  I'd like to be able to link directly to different sections at different times for more focused attention as each topic is relevant to their work.  Adding section headings with anchor tags and [easily-copied links](https://ux.stackexchange.com/questions/36304/use-of-mouse-over-paragraph-marker-in-headlines-for-permalink) would make the page much more usable for cases like this.

**Comment by desmodrone** [comment]
@liffiton thanks for this suggestion it sounds like a good idea!

**Comment by fasterthanlime** [comment]
@liffiton I just added about a gazillion headings to the article, hopefully this is useful!

**Comment by liffiton** [comment]
Thanks!  That looks great!  I've put it on my todo list to use it next time I teach the class.
