### ISSUE TITLE
Developing over SSH

### ISSUE THREAD

**Issue by elyalon** [bearcove/feedback#271]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-2#position=71.9

  Here's what it is:
![image](https://github.com/fasterthanlime/feedback/assets/105967627/db2d4d0f-3311-4683-90cb-c8517b5535a0)
-bind instead of --bind

**Comment by desmodrone** [comment]
@2crayon thanks for finding this, I've fixed it. Cheers!
