### ISSUE TITLE
Article issue - Rust modules vs files 

### ISSUE THREAD

**Issue by bnzone** [bearcove/feedback#272]
_Love your content! I'm getting into Rust and for me this is probably the best explanation for Rust modules/files system that I've read.
Thank you for what you do!_

## It happened on this page

Link to the page, make sure to point out which paragraph it's in.
https://fasterthanli.me/articles/rust-modules-vs-files

> Indeed, we don't use sub in main right now. What happens if we remove `its` _(it?)_ from the use directive? ie., if we change src/main.rs to:

> As expected, this builds and `run` _(runs?)_ just fine:

## Here's what the issue is

I think there's just a few small typos in the paragraphs mentioned above (I highlighted the words)

**Comment by desmodrone** [comment]
@bnzone thanks for catching these, I've fixed them in the article!
