### ISSUE TITLE
What's in a Linux executable?

### ISSUE THREAD

**Issue by noamraph** [bearcove/feedback#274]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-executable-packer/part-1#position=24.8

  Here's what it is:

I got a bit confused by:

```
$ cargo new --bin elk
$ cargo add --path ../delf
      Adding delf (unknown version) to dependencies
```

I suggest to add `cd`s. Perhaps:

```
$ cd ..   # Go back to the parent of the `delf` directory
$ cargo new --bin elk
$ cd elk
$ cargo add --path ../delf
      Adding delf (unknown version) to dependencies
```

Thanks, I'm enjoying the guide a lot!
Noam

**Comment by fasterthanlime** [comment]
I just added that missing cd, thanks for the report!
