### ISSUE TITLE
Potentially misdirected link on Figma article

### ISSUE THREAD

**Issue by jaxter184** [bearcove/feedback#275]
## It happened on this page

https://fasterthanli.me/articles/just-paying-figma-15-dollars

> After much trial and error, I came up with the following [k3s manifest](https://fasterthanli.me/articles/just-paying-figma-15-dollars):

## Here's what the issue is

the link just points to the article. I assume it's supposed to point to a file somewhere?

**Comment by fasterthanlime** [comment]
Fixed, thanks!
