### ISSUE TITLE
Reading files the hard way - Part 2 (x86 asm, linux kernel)

### ISSUE THREAD

**Issue by barnabywalters** [bearcove/feedback#283]
I found something wrong on this page:

  https://fasterthanli.me/series/reading-files-the-hard-way/part-2#position=40.4

In

> In very simple terms: a C compiler translate C to assembly, the assembler translate assembly to machine code, and a linker glues together several pieces of machine code into an executable.

two uses of “translate” should be “translates“, i.e.

> In very simple terms: a C compiler translates C to assembly, the assembler translates assembly to machine code, and a linker glues together several pieces of machine code into an executable.

**Comment by fasterthanlime** [comment]
Good catch! All fixed.
