### ISSUE TITLE
Crafting ARP packets to find a remote host's MAC address

### ISSUE THREAD

**Issue by barnabywalters** [bearcove/feedback#287]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-ping/part-13#position=7.3

“whish” should be “which”

**Comment by barnabywalters** [comment]
And in the next sentence, ”MAC” is written as “mac”, whish  is inconsistent with the rest of the article

**Comment by fasterthanlime** [comment]
Fixed, thanks!
