### ISSUE TITLE
typo in Generating a docker image with nix

### ISSUE THREAD

**Issue by lentil32** [bearcove/feedback#288]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-11#position=30.6

  Here's what it is:
  
  > Let's first try to make a docker image with just our binary: we know it won't be enough, since we --> **neeed** <-- to have the geo-ip database in there, but it's a start.

From `neeed` to `need` needed.

Thanks.

**Comment by fasterthanlime** [comment]
Fixed, thanks!
