### ISSUE TITLE
What's in a Linux executable?

### ISSUE THREAD

**Issue by sid-kap** [bearcove/feedback#292]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-executable-packer/part-1#position=13.0

  Here's what it is:

In elf64-file-header.bfa657ccd8ab3a7d.svg, Flags (u32) is shown as being 2 bytes, but it should be 4 bytes. 
These byte offsets are wrong: Flags should be 48 to 52, Header size should be 52 to 54, and Entry size should be 54 to 56. Everything after that is correct.

**Comment by fasterthanlime** [comment]
You're right! I just fixed it, thanks for the report.
