### ISSUE TITLE
Subheaders are nearly invisible in dark mode

### ISSUE THREAD

**Issue by SophieSilver** [bearcove/feedback#294]
(from [Just paying Figma...](https://fasterthanli.me/articles/just-paying-figma-15-dollars))
Here's how headers look in light mode:
![image](https://github.com/fasterthanlime/feedback/assets/87021304/7f0a6038-415c-44fc-a742-0a51b90ae897)

And here they are in dark mode
![image](https://github.com/fasterthanlime/feedback/assets/87021304/73ee93de-6e95-49b2-bec9-a1bbdd674186)

This seems to happen in nearly all articles

**Comment by fasterthanlime** [comment]
I do remember fixing this, I guess I accidentally deployed that fix today while doing something else? Anyway, thanks for reporting!
