### ISSUE TITLE
No interactivity on `Day 9 (Advent of Code 2022)`

### ISSUE THREAD

**Issue by Invariance-NaN** [bearcove/feedback#295]
I found something wrong on this page:

  https://fasterthanli.me/series/advent-of-code-2022/part-9#position=65.7

  Here's what it is:

The embeds for the solutions do not load, apparently because of a MIME type mismatch.
![image](https://github.com/fasterthanlime/feedback/assets/51858957/e4dd3cd9-38ed-4cc8-a7b4-4e3c5764b68c)
(The embeds are just empty background-colored rectangles.)

I'm using Firefox Dev edition 124.0b3.

**Comment by fasterthanlime** [comment]
This is fixed now, thanks for reporting!

---

For the curious: I recently spinned up a new domain, `cdn.fasterthanli.me`, to serve static assets, and I made sure that most things: images, stylesheets, javascript files, etc., were cachebusted. These WASM embeds are generated by https://trunkrs.dev/ and have lines like:

```
import init from './day9-87799ff6864ed5e8.js';init('./day9-87799ff6864ed5e8_bg.wasm');
```

Which aren't cachebusted, or at least not in the way my custom CMS cachebusts things (a typical CDN asset url is `https://cdn.fasterthanli.me/content/series/advent-of-code-2022/part-9/assets/part1-wasm/index.1be165d2e13f9ec6.html`)
