### ISSUE TITLE
Broken link in: Just paying Figma $15/month ...

### ISSUE THREAD

**Issue by hayesall** [bearcove/feedback#297]
I found something wrong on this page:

  https://fasterthanli.me/articles/just-paying-figma-15-dollars#position=27.6

It looks like the `.html` was stripped from the end of `https://drewdevault.com/2020/03/18/Reckless-limitless-scope`, resulting in a 404 error after clicking the link.

**Comment by fasterthanlime** [comment]
Fixed, thanks!
