### ISSUE TITLE
Lies we tell ourselves to keep using Golang

### ISSUE THREAD

**Issue by NathanWailes** [bearcove/feedback#298]
Better options than Go for web dev / APIs?

I just spent a few hours going through and summarizing the two blog posts on Go and I'm wondering if Rust is the only better alternative to Go that you'd recommend for a web app / API backend or if you'd say that there are other preferable alternatives (Node.js / Java / C#, for example).

**Comment by fasterthanlime** [comment]
You'd have better luck asking around on social media :)

I'm partial to Rust, a bunch of companies are adopting it for web backend work (see Luca Palmieri's posts on Twitter etc.), but it's certainly not the only game in town.
