### ISSUE TITLE
'View Full Patron List' button not working

### ISSUE THREAD

**Issue by BerryArray** [bearcove/feedback#309]
## Problem

At the bottom of every article on the website, there's the showcased patrons list. A link at the end of the list ('... and 240 more') is supposed to replace the showcased patrons list with the full list, but it currently doesn't do anything.

## Potential reason

In the function that handles the click, there's this line:
`let patronList = document.querySelector("#patron-list");`
... despite the element having `id="sponsor-list"`.
Chances are the `id` was changed but this line wasn't, causing the bug.

---

_More info:_
- OS: Windows 10
- Browsers: Firefox and Chrome (same situation)

**Comment by fasterthanlime** [comment]
Fixed!
