### ISSUE TITLE
Lies We Tell Ourselves To Keep Using Golang Typo

### ISSUE THREAD

**Issue by stelcodes** [bearcove/feedback#34]
https://fasterthanli.me/articles/lies-we-tell-ourselves-to-keep-using-golang

Paragraph:
The "correct" way to assume an optional value is set is to assert that it is, not to use it regardless. That's the difference between calling json.Unmarshal and crossing your fingers, and calling [unwrap()](https://doc.rust-lang.org/stable/std/option/enum.Option.html#method.unwrap) on an Option<T>.

`is set is to assert`

Should probably be: `is to assert`

**Comment by fasterthanlime** [comment]
I did mean to write that way, but I added a comma for clarity.

**Comment by stelcodes** [comment]
Oh duh 😆 My bad!
