### ISSUE TITLE
I won free load testing: Never using ArcSwap in update_ip_nets

### ISSUE THREAD

**Issue by haved** [bearcove/feedback#43]
**Where's the problem at?**
[Please link to the article](https://fasterthanli.me/articles/i-won-free-load-testing)

**No, seriously, where is it?**
In the definition of `update_ip_nets`, I can't seem to find any calls to `ip_nets_handle.store()`. Code taken from the site:
```rust
async fn update_ip_nets(ip_nets_handle: &ArcSwap<HashSet<IpNet>>) -> color_eyre::Result<()> {
    let client = reqwest::Client::new();
    tokio::time::sleep(Duration::from_secs(15)).await;

    let mut sources = vec![IPS_LOCAL.to_string()];
    for url in [
        "https://www.cloudflare.com/ips-v4",
        "https://www.cloudflare.com/ips-v6",
    ] {
        sources.push(client.get(url).send().await?.text().await?);
    }
    let sources: Vec<_> = sources.iter().map(|x| x.as_str()).collect();
    let ip_nets = parse_ip_nets(&sources[..])?;
    info!(
        "Loaded {} ip nets (had {})",
        ip_nets.len(),
        ip_nets_handle.load().len()
    );

    Ok(())
}
```

**Describe the issue and a fix if you know it**
This might not even be an issue, but nothing seems to be stored into the `ip_nets_handle` parameter, it is only ever `load()`-ed.
I tried looking at the docs, would it make sense to add, after the `info!`:
```rust
ip_nets_handle.store(ip_nets);
```

Sorry if I'm missing something, cheers

**Comment by fasterthanlime** [comment]
Good catch! Another logic error makes it through 🥲

I really should hire some folks to help review my code! (The store call got lost in the shuffle)

In the meantime, I've fixed the article and my website. Thanks so much for the report.
