### ISSUE TITLE
I won free load testing - RSS reader statistics query filters out too much

### ISSUE THREAD

**Issue by mateon1** [bearcove/feedback#45]
I found something wrong on this page:

https://fasterthanli.me/articles/i-won-free-load-testing#position=69.0

Here's what it is:

The RSS reader query filters out a lot of potentially interesting data by filtering out "Mozilla/5.0".
I personally use Thunderbird for everything from IRC to RSS, and a quick check gives me the following headers when setting up a feed:
<details>
<summary>Thunderbird request headers (click to expand)</summary>

```http
GET /index.xml HTTP/1.1
Host: localhost:8000
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Thunderbird/91.6.1
Accept: application/atom+xml,application/rss+xml;q=0.9,application/rdf+xml;q=0.8,application/xml;q=0.7,text/xml;q=0.7,*/*;q=0.1
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
If-Modified-Since: Sat, 01 Jan 2000 00:00:00 GMT
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: cross-site
Pragma: no-cache
Cache-Control: no-cache
```

</details>

Note the user agent.

I'd love to see the data for a full-er query.

**Comment by fasterthanlime** [comment]
I added a more extensive list, without filtering out "Mozilla/5.0".
