### ISSUE TITLE
r2d2_sqlite crate link uses incorrect URL

### ISSUE THREAD

**Issue by Benjins** [bearcove/feedback#46]
**Where's the problem at?**
https://fasterthanli.me/articles/i-won-free-load-testing

**No, seriously, where is it?**
```
So, immediately, I jump back to the code and find a ton of actionable information there: for example, the size of my "connection pool" is only 10 [r2d2-sqlite](https://lib.rs/crates/r2d2-sqlite)'s default: under load, that's not enough.
```

**Describe the issue and a fix if you know it**
The link to https://lib.rs/crates/r2d2-sqlite should instead be https://lib.rs/crates/r2d2_sqlite (the hyphen should be an underscore) I'm not sure if the crate was renamed, but that's where it lives now.

**Comment by fasterthanlime** [comment]
Fixed, thanks!
