### ISSUE TITLE
Video player does nothing on iOS

### ISSUE THREAD

**Issue by semicoleon** [bearcove/feedback#5]
I'm not sure if you just decided not to support iOS (since it's kind of picky), but if so it might be good to try and show an error message.

Currently it just does nothing when I hit play, the thumbnail never shows up, and the timestamp continues to show 0:00/0:00

Though sometimes the first time becomes NaaN:NaaN

**Comment by fasterthanlime** [comment]
Thanks for the report! That completely slipped my mind.

The good news is: shaka-player does support iOS (via HLS) and shaka-packager does support emitting HLS playlists. So in theory, it's doable. Also, I plan to do it.

The bad news is: I don't really have a great way to test it - save from the iOS simulator on a mac. So I guess I'll try that! I'll update this thread if/when I get some results.

**Comment by Xaeroxe** [comment]
Here’s a screenshot from my phone
![B31B3BDF-1175-4BC6-8AD8-C53213CA3A4B](https://user-images.githubusercontent.com/6182002/163305169-0c86a826-0d14-45d2-b728-f928ba695b46.png)

**Comment by fasterthanlime** [comment]
Thanks. I bought an iPhone 7 just to test this, it arrived today, will keep y'all posted!

**Comment by Xaeroxe** [comment]
Works for me now!

**Comment by Xaeroxe** [comment]
Though, the fullscreen button isn't doing anything

**Comment by fasterthanlime** [comment]
> Works for me now!

Are you.. a time traveler? or using an iPad?

I just finished re-encoding the video as AVC/H.264 (720p and 1080p only) and it _just now_ started working on my iPhone 7 (iOS 15.4 iirc).

> Though, the fullscreen button isn't doing anything

I've experienced that too. Maybe Mobile Safari will start supporting it someday...

![image](https://user-images.githubusercontent.com/7998310/163893905-e12957fe-f01e-406e-88ee-d9fd99d62062.png)

cf. https://caniuse.com/?search=fullscreen

---

@semicoleon can you confirm that it works for you too?

**Comment by semicoleon** [comment]
Working on iPad now (so is full screen mode, interestingly)!

**Comment by fasterthanlime** [comment]
Note that the video is also now available on YouTube, as the page shows, just unlisted so far - I wanted to fix the player on iOS before I announced it publicly :)

**Comment by Xaeroxe** [comment]
> Are you.. a time traveler? or using an iPad?

this was definitely on my iPhone. Your guess is as good as mine.
