### ISSUE TITLE
Re-add logged-out theme override because OSes/browsers suck and user settings aren't discoverable enough

### ISSUE THREAD

**Issue by joaocarvalhoopen** [bearcove/feedback#51]
Hello,
Please make your site Dyslexic friendly by making a dark mode option in it.

Best regards,
João

**Comment by fasterthanlime** [comment]
Ah, but it's had a dark mode forever.

It follows the device theme: for me this works on both Firefox & Chrome on Windows, and both these browsers on Android too. On Linux it doesn't do jack shit because that's apparently a hard thing to do.

Also, if you log in with Patreon (you don't need to subscribe to me, just log in), you can override it in your user settings.

But since it's the third time I need to write this exact comment, you're right and I'm wrong, and I'm gonna re-add a logged-out override.

**Comment by fasterthanlime** [comment]
And there it is: 
![Uploading image.png…]()

**Comment by joaocarvalhoopen** [comment]
Hello Amos,

thank you very much,
it's really nice and really better!
To be perfect for dyslexic and low vision people, and for people that is in front of a computer from early in the morning to late at night, there is only one thing that it could be better, it is to not have the white for the letters and have something more soft for the cones in the eyes with less blue component like for example the color:

```
#b5bd68
```

Thank you very much!
You effort is really appreciated. 

The very bet wishes,
João

**Comment by joaocarvalhoopen** [comment]
![image](https://user-images.githubusercontent.com/6319988/167243549-5f1aa059-c2b6-4ed5-b36a-54ed58daf35c.png)

**Comment by fasterthanlime** [comment]
> there is only one thing that it could be better, it is to not have the white for the letters and have something more soft for the cones in the eyes with less blue component like for example the color

Mhhh I could see myself reducing contrast a _little_ (as long as it's still above the recommended WCAG contrast), the specific color you recommended is.. very yellow though.

I'm curious, do you use something like Redshift / some Night light-like feature? For me this solves the problem altogether without each site having to have their own custom theme.

**Comment by joaocarvalhoopen** [comment]
No I don't use anything,

What I use is Linux Ubuntu as my system, Visual Studio Code that is normally dark, use Sioyek with in custom_color mode, Zettlr with custom CSS and use Geany with custom color mode, all with a color similar to the one I sent you, except VSCode :-)

Many times if the text is on the web and is long I hit F12 and edit the CSS in a rapid way. But your site is one that have very long texts that I like to read particularly slowly  because of it's quality and knowing that you are tech savvy and that you care, I opened the issue.

I have to read what is Redshift, I don't like the night light features on most computers.
But my computer is on from 7H in the morning to 24H everyday, so saving on the eyes is a must :-)

Best regards,
João

**Comment by fasterthanlime** [comment]
Here's my suggestion: file another issue on this repo, with a clear title & description and a proposed color scheme. This'll allow folks to vote on it. I'd like to see this discussed too: how can we make this discoverable without it being obnoxious. Currently the light/dark button is a toggle. Would it then become a dropdown menu?

Thanks!
