### ISSUE TITLE
Rust modules vs files

### ISSUE THREAD

**Issue by fasterthanlime** [bearcove/feedback#54]
I found something wrong on this page:

  https://fasterthanli.me/articles/rust-modules-vs-files#position=31.6

  Here's what it is:

The heck is that:

![image](https://user-images.githubusercontent.com/7998310/167272099-82e624fd-ae4d-421a-b038-7e54df41cc7f.png)

**Comment by jasikpark** [comment]
I think that maybe `<code/>` is an invalid child of a heading element?

<img width="996" alt="image" src="https://user-images.githubusercontent.com/10626596/167439446-14846206-5aa3-4228-ad10-d33df8b6ecb7.png">

^^ testing with a manually added code element; so maybe your markdown generator did something wonky?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content

nope, nvm

**Comment by jasikpark** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/10626596/167439828-dd4957ed-42d0-4c7b-a6ad-e21743cc4fe5.png">
 
yup nvm

**Comment by fasterthanlime** [comment]
I fixed it!

**Comment by jasikpark** [comment]
I'm curious, was it a markdown parsing problem?

**Comment by jasikpark** [comment]
ohh cool that's wacky that it parses/prints that way

**Comment by fasterthanlime** [comment]
> ohh cool that's wacky that it parses/prints that way

I take full responsibility for this one honestly, I'm doing pretty weird stuff that doesn't combine super well with the event-based model.
