### ISSUE TITLE
Block of code is not using syntax highlighting

### ISSUE THREAD

**Issue by Shikada** [bearcove/feedback#6]
**Where's the problem at?**
[Please link to the article](https://fasterthanli.me/series/making-our-own-ping/part-9)

**No, seriously, where is it?**
Block of code comes after this text:
**The context combinator allows us to add some, well, context, to our errors. In other words it allows us to attach to our errors information about what it is we were trying to parse.

Let's use it now:**

**Describe the issue and a fix if you know it**
Code block is not set as a rust code block.

**Comment by fasterthanlime** [comment]
Fixed, thanks!
