### ISSUE TITLE
Futures Nostalgia

### ISSUE THREAD

**Issue by leakingtapan** [bearcove/feedback#8]
I found something wrong on this page:

https://fasterthanli.me/articles/futures-nostalgia#position=2.8

Here's what it is:

The print statement should be
```rust
println!("Handling {req:?}", req = req);
```
Otherwise, I got following error:
```rust
error: there is no argument named `req`
  --> src/main.rs:46:28
   |
46 |         println!("Handling {req:?}");
   |                            ^^^^^^^

error: could not compile `nostalgia` due to previous error
```

**Comment by fasterthanlime** [comment]
You need to upgrade your rust compiler :) That's Rust 2021 syntax.

**Comment by leakingtapan** [comment]
Cool. upgrading it to 1.60 worked for me. It will be good to highlight the minimum required rust version then.
